Update UserService.changeEmail and UserServiceTest. Create ChangeMail…
hosu794/juniorstart-backend pull request #20
Opened 2020-09-02 16:14 UTC by noboseki

…Request for Controller. Add method to UserDaoImpl

2020-09-02 16:17 UTC, hosu794 submitted a review, later dismissed

2020-09-02 16:57 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/service/UserService.java
> +        User user = userDao.findByNameAndPassword(changeMail.getName(), changeMail.getPassword())
Nie lepiej dać przekazać zmienne z konstruktora, zamiast tworzyć niepotrzebnego obiektu?

2020-09-02 17:37 UTC, Ejden requested changes

2020-09-02 17:37 UTC, Ejden commented on src/main/java/com/juniorstart/juniorstart/service/UserService.java
> +        User user = userDao.findByNameAndPassword(changeMail.getName(), changeMail.getPassword())
Zgadzam się. Ten ChangeMailRequest jest tutaj niepotrzebny. Zmienić :P

2020-09-03 17:16 UTC, hosu794 approved these changes, later dismissed

2020-09-03 17:50 UTC, Ejden reviewed
Trzeba rozwiązać konflikty

2020-09-03 18:49 UTC, Ejden approved these changes

2020-09-03 19:08 UTC, hosu794 approved these changes

2020-09-03 19:08 UTC, merged