Create Goal entity, Dto, service, serviceTest and controller.
hosu794/juniorstart-backend pull request #39
Opened 2020-09-27 13:58 UTC by noboseki

Metody stworzone dla CRUD, nie uzgodniliśmy jakie metody mają być w serwsie. W przyszłości się rozbuduje serwis tak jak UserService.

2020-09-27 14:46 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/controller/GoalController.java
> + * @since 1.0
Przyjeliśmy już, że używamy nazewnictwa NazwaRequest albo NazwaResponse itp.

2020-09-27 14:48 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/service/GoalService.java
> +    public ResponseEntity<Set<Goal.GoalDto>> getAll(@Valid  GetGoalRequest request) {
Nie lepiej dać adnotacje @CurrentUser?

2020-09-27 14:49 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/service/GoalService.java
> +    public ResponseEntity<ApiResponse> update(@Valid Goal.GoalDto dto){
@CurrentUser

2020-09-27 14:50 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/service/GoalService.java
> +    public ResponseEntity<ApiResponse> delete(@Valid DeleteGoalRequest request) {
Sprawdzenie czy obecnie zalogowany użytkownik jest twórcą Goala.

2020-09-27 14:50 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/service/GoalService.java
> +     */
Czemu szuka po haśle?

2020-09-27 14:51 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/service/GoalService.java
> +     * @return User from repository to change chosen data.
Nie wiem czy jest sens w rozdrabnianiu tak metod, ale nie inni się wypowiedzą.

2020-09-27 19:33 UTC, Ejden commented
Niepoprawna nazwa taska. Brak numeru

2020-09-27 19:44 UTC, Ejden requested changes

2020-09-27 19:44 UTC, Ejden commented on src/main/java/com/juniorstart/juniorstart/model/Goal.java
> +    public Goal mapToEntity(GoalDto goalDto) {
Hmm, nie lepiej tego zrobić jako statyczną metodę?

2020-09-27 19:44 UTC, Ejden commented on src/main/java/com/juniorstart/juniorstart/model/Goal.java
> +    public Goal mapToEntity(GoalDto goalDto) {
I nazwać może w stylu getGoalFromGoalDto Czy jakoś tak. Tak żeby po prostu stworzyć metodę która tworzy obiekt, bo tworzenie goal, żeby zrobić goal jest trochę bez sensu :P

2020-09-27 19:44 UTC, Ejden commented on src/main/java/com/juniorstart/juniorstart/model/Goal.java
> +    public Set<GoalDto> mapToDtos(Set<Goal> goals) {
Zamiast umieszczania tego tutaj pomyślałbym po prostu nad robieniem tego w serwisie czy gdzie tam to potrzebujesz. Tak żeby tam zrobić 
```Java
goals.stream().map(Goal::mapToDto).collect(Collectors.toSet());
```

2020-09-27 19:44 UTC, Ejden commented on src/main/java/com/juniorstart/juniorstart/payload/DeleteGoalRequest.java
> +    private UUID userPrivateId;
Użytkownik nie ma pojęcia jakie ma UUID. Wie za to jakie ma Long userId. Tak samo powinno być z Goal. Czyli entity które zwracane są na front mają UUID jako domyślne ID i Long jako NaturalID. Czyli np. User ma te privateId i UserId i tak samo tu Goal powinien mieć privateId (albo Id nazwane, idk jak tam się stosuje, a dodatkowo Long goalId, które będzie zwracane na front)

2020-09-27 19:44 UTC, Ejden commented on src/main/java/com/juniorstart/juniorstart/service/GoalService.java
> +     * @return User from repository to change chosen data.
Jest sens :P

2020-09-29 16:21 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/controller/GoalController.java
> +        return service.getAll(request);
Czemu nie zwraca Pageable z wartościami?

2020-09-29 16:21 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/controller/GoalController.java
> +        return service.create(dto);
Lepiej dla frontu, jak zwraca metoda utworzony obiekt.

2020-09-29 16:22 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/controller/GoalController.java
> +    }
Lepszym rozwiązanie będzie napisanie metody, aby zwracała ResponseEntity z ApiResponse

2020-09-29 16:23 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/model/Goal.java
> +    public Set<GoalDto> mapToDtos(Set<Goal> goals) {
To można przerobić na mapToGoalResponse, gdzie będzie miała też creatora.

2020-09-29 16:24 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/service/GoalService.java
> +     * @return User from repository to change chosen data.
Ok :)

2020-10-01 17:02 UTC, hosu794 approved these changes

2020-10-10 12:31 UTC, Ejden commented
Co z tym pullem?

2020-10-20 16:14 UTC, closed without merging