Update README.md
hosu794/juniorstart-backend pull request #45
Opened 2020-10-10 13:52 UTC by noboseki

2020-10-10 13:56 UTC, Ejden requested changes

2020-10-10 13:56 UTC, Ejden commented on README.md
> +LOGS_DATABASE_DRIVER_PATH=
Ja bym to zrobił jako kod

2020-10-10 15:39 UTC, noboseki commented on README.md
> +LOGS_DATABASE_DRIVER_PATH=
oki

2020-10-10 18:08 UTC, Ejden approved these changes

2020-10-10 18:08 UTC, Ejden commented on README.md
> +LOGS_DATABASE_DRIVER_PATH=
W sensie cały ten plik env dać w ``` o ile tak się oznacza kod w md

2020-10-11 11:37 UTC, hosu794 approved these changes

2020-10-11 11:37 UTC, merged