Wysyłanie wiadomości przez użytkowników (Wersja prototypowa) (Ocena innych)
hosu794/juniorstart-backend pull request #56
Opened 2020-11-10 19:43 UTC by hosu794

Wersja prototypowa funkcji wysyłania wiadomości pomiędzy użytkownikami.  Napisałem też testy jednostkowe i integracyjne :)

2020-11-11 20:40 UTC, p-krukowski requested changes
Na tyle na ile ogarniam to posprawdzałem. Ogólnie czepiłbym się, że niektóre linie są dość długie i w pewnych miejscach bym je ucinał, żeby nie trzeba było scrollować w poziomie. Niektóre funkcje są też dość długie i proponuje rozbijać je na mniejsze, żeby po nazwie samej funkcji było wiadomo co się dzieje (zgodnie z poradami wujka Boba, rozbijaj funkcje na mniejsze, tak długo jak to jest możliwe). I też zobaczyłem że w wielu miejscach jest sporo pustych linii, nie za bardzo wiem po co.

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/bootstrap/ApplicationLoader.java
> +            User user = User.builder().email("someEmail")
tutaj nie uwaga do tego kodu, tylko pytanie czy pole email w User nie powinno być validowane i wtedy takie coś nie powinno przejść?

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/controller/UserController.java
>      }
Czemu nie wykorzystać tutaj Lomboka?

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/controller/UserController.java
> +    private UserSummary convertTo(User user) {
Proponuje zmienić nazwę na convertToUserSummary albo getUserSummary

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/service/ChatMessageService.java
> +        String chatId = chatRoomService.getChatId(chatMessage.getSenderId(), chatMessage.getRecipientId(), true).orElseThrow(() -> new BadRequestException("Cannot find a chatId"));
Proponuje wrzucić gdzieś nową linie

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/service/ChatRoomService.java
> +    }
Chyba bym to jednak rozbił na krótsze funkcje

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/service/ProjectService.java
> +            return new PagedResponse<>(Collections.emptyList(), projects.getNumber(), projects.getSize(), projects.getTotalElements(), projects.getTotalPages(), projects.isLast());
Wrzuciłbym gdzieś nową linię

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/service/ProjectService.java
> +        return new PagedResponse<>(projectResponses, projects.getNumber(), projects.getSize(), projects.getTotalElements(), projects.getTotalPages(), projects.isLast());
Wrzuciłbym gdzieś nową linię

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/service/ProjectService.java
> +
Proponuje wyrzucić do zewnętrznej funkcji

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/service/ProjectService.java
> +            return new PagedResponse<>(Collections.emptyList(), projects.getNumber(), projects.getSize(), projects.getTotalElements(), projects.getTotalPages(), projects.isLast());
Wrzuciłbym gdzieś nową linię

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/service/ProjectService.java
> +        }).getContent();
Tutaj też proponuję zrobić nową funkcję

2020-11-11 20:40 UTC, p-krukowski commented on src/main/java/com/juniorstart/juniorstart/JuniorstartApplication.java
> +    }
Co to?

2020-11-12 20:38 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/JuniorstartApplication.java
> +    }
zapomniałem usunąc :)

2020-11-14 08:49 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/bootstrap/ApplicationLoader.java
> +            User user = User.builder().email("someEmail")
private boolean checkBootstrap() {
        boolean isUser = userDao.findByEmail("someEmail").isEmpty();

        return isUser;
    }

Coś w tym stylu?

2020-11-14 08:55 UTC, hosu794 commented on src/main/java/com/juniorstart/juniorstart/controller/UserController.java
> +    private UserSummary convertTo(User user) {
Będę musiał to przenieść do do serwisu

2020-11-14 10:28 UTC, closed without merging